// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJTgifvhewc-sDD60kb_XNRpwz7GKFJB4',
    appId: '1:892480749232:web:6d75e26bcc8c9534fa8575',
    messagingSenderId: '892480749232',
    projectId: 'salonbooking-58b28',
    authDomain: 'salonbooking-58b28.firebaseapp.com',
    storageBucket: 'salonbooking-58b28.appspot.com',
    measurementId: 'G-EWQVWB4XMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_nT5siSHjic3bJ2q-A8Ss64kWR8xOBdM',
    appId: '1:892480749232:android:8c6759f968f389c6fa8575',
    messagingSenderId: '892480749232',
    projectId: 'salonbooking-58b28',
    storageBucket: 'salonbooking-58b28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCmOLY9eMyr07w2wXOZhqgZW9FOMHnslQ',
    appId: '1:892480749232:ios:953359f442ec9bb2fa8575',
    messagingSenderId: '892480749232',
    projectId: 'salonbooking-58b28',
    storageBucket: 'salonbooking-58b28.appspot.com',
    iosClientId: '892480749232-qgu23kqj882tv2o74isj612k87iesfc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCmOLY9eMyr07w2wXOZhqgZW9FOMHnslQ',
    appId: '1:892480749232:ios:953359f442ec9bb2fa8575',
    messagingSenderId: '892480749232',
    projectId: 'salonbooking-58b28',
    storageBucket: 'salonbooking-58b28.appspot.com',
    iosClientId: '892480749232-qgu23kqj882tv2o74isj612k87iesfc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJTgifvhewc-sDD60kb_XNRpwz7GKFJB4',
    appId: '1:892480749232:web:0f24221e0104c2ebfa8575',
    messagingSenderId: '892480749232',
    projectId: 'salonbooking-58b28',
    authDomain: 'salonbooking-58b28.firebaseapp.com',
    storageBucket: 'salonbooking-58b28.appspot.com',
    measurementId: 'G-EJJ6Q5M4QH',
  );

}